Repository MePill/22-F-Cow-ClubCommunity, pull requests merged in 2022-11, with the labels that each got.

#2 Init; install express, ejs, body-parser, nodemon
  .gitignore
  app.js
  package-lock.json
  package.json
Labels: ✅완료, 영환

#4 Feat; main.html,css추가
  .gitignore
  public/css/main.css
  views/main.html
Labels: 영환, 👀리뷰

#3 Feat; main.js에서 sendFile로 html파일과 css 파일 연결
  app.js
Labels: 영환, 👥논의필요

#5 Feat; 글작성 페이지 html, css
  public/css/create.css
  public/css/login.css
  views/create.html
  views/login.html
Labels: 영환, 👀리뷰, 👥논의필요

#6 Feat; 작성,로그인 페이지 서버 연결
  app.js
Labels: 영환, 👀리뷰

#7 Feat; Header 버튼 기능 활성화
  views/create.html
  views/login.html
  views/main.html
Labels: ✅완료, 영환

#8 Style; html에서 ejs로 변경
  views/create.ejs
  views/main.ejs
Labels: 영환, 👥논의필요

#9 Feat; Create 완성
  app.js
Labels: ✅완료, 영환

#10 Feat; main 목록에서 read 페이지 이동하는 기능 구현
  app.js
Labels: ✅완료, 영환, 👥논의필요

#11 Feat; main에 목록에 해당하는 페이지 이동 추가 해당하는 페이지 작성
  views/main.ejs
  views/view.ejs
Labels: ✅완료, 영환, 👨🏻‍💻작업중

#13 chore; .gitignore에 폴더 추가
  .gitignore
Labels: ✅완료, 영환

#14 Feat; 뒤로가기 버튼 bug 수정
  views/create.ejs
Labels: ✅완료, 영환

#15 Feat; +update 페이지도 수정
  views/update.ejs
Labels: ✅완료, 영환

#17 init
  package-lock.json
  package.json
Labels: ✅완료, 고건

#18 Chore; update, view 수정
  views/create.ejs
  views/update.ejs
Labels: ✅완료, 고건

#19 Chore; app.js 수정
  app.js
Labels: 고건, 👨🏻‍💻작업중

#21 Chore; Update.js 빈칸 에러 수정
  app.js
Labels: ✅완료, 고건

#22 Feat; 메인페이지 삭제 기능 추가
  app.js
Labels: 고건, 👥논의필요

#23 Feat; Delete페이지 추가
  public/css/delete.css
  views/delete.ejs
  views/main.ejs
  views/view.ejs
Labels: 고건, 👥논의필요

#27 Feat; 컨트롤러 모델 라우터 분리, 로그인 유지 및 로그 아웃 기능
  app.js
  controllers/postController.js
  controllers/userController.js
  model/userModel.js
  package.json
  routes/postRouter.js
  routes/userRouter.js
Labels: ✅완료, 영환
